# Generated by Django 4.0.10 on 2023-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('maksja', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('saaja', models.CharField(max_length=100)),
                ('rahahulk', models.CharField(max_length=100)),
            ],
        ),
    ]
