# Generated by Django 4.0.10 on 2023-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgneja', models.CharField(max_length=100)),
                ('volgnetav', models.CharField(max_length=100)),
                ('raha', models.TextField()),
            ],
        ),
    ]
