# Generated by Django 4.0.10 on 2023-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodutoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('maksja', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('saaja', models.CharField(max_length=100)),
                ('rahahulk', models.CharField(max_length=100)),
            ],
        ),
    ]
