# Generated by Django 4.0.10 on 2023-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodutoo', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makse',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pohjus',
            field=models.CharField(default='Söök', max_length=150),
        ),
    ]
